const arr = new Map();
arr.set('Plumber', {
  name: 'Plumbing',
  learningOutcome: [
    'List the five procedures for solvent welding ABS pipe',
    'Build and design a functional or decorative structure from ABS Pipe and fittings',
    'Conduct safe work practices with common plumbing equipment',
    '	Analyze a solder joint',
    'Recognize career & education opportunities relating to plumbing',
  ],
  itaResource: ['Solvent Welding', 'Solder', 'Fixture installation'],
  ppeRequirement: [
    'Safety Glasses (Eye Protection)',
    ' Gloves',
    'Steel Toe Boot (Close Toe)',
    ' Good Ventilation',
  ],
  projectDescription:
    'Students will gain plumbing experience through the creation of a functional or decorative structure of their own design. The creation of the structure will explore plumbing process such as stock layout, breakout and solvent welding. An introduction to copper soldering will follow.',
  equipmentNeeded: [
    'Plastic pipe cutter, hack saw or mitre saw',
    'De-burring tool and/or emery cloth',
    'Copper pipe cutter',
    'Copper fittings, T’s and  caps',
    'Push connect TEE (optional)',
    'Propane torch and striker',
  ],
  materialNeeded:
    '1.5” ABS Pipe\nABS fittings: P-trap, WYEs, pipe cap, 45° & 90° elbow\nABS Cement\n.5” copper pipe\nSolder (lead free) , Flux & Brush\n',
  dailyPlan: [
    'Into to trade, tools and daily objectives',
    'Brain storming and ideation',
    'Stock breakout and start of work time',
    'Assembly and finishing up',
    'Break',
    'Copper pipe and solder intro',
    'Practice soldering, simple copper shape',
    'Clean Up',
    'Buffer time',
    'End Of Lesson Routine:',
    'Project show case, handouts & next steps…',
  ],
  time: [
    '15m',
    '30m',
    '45m',
    '20-30m',
    '15m',
    '15m',
    '30-45m',
    '15m',
    '10m',
    '',
    '15m',
  ],
  learningSupports: [
    'Power point',
    'Pencil, paper & and ideas',
    'Support ideas & help create',
    'Quick glue demo',
    '',

    'Solder demonstrate',
    ' Handout then pressure test',
    ' Discuss expectation',
    '',
    '',
    'Career/Ed opportunities..',
  ],
  lessonSummary: 'How did the class go?',
});

arr.set('Automotive', {
  name: 'Automotive Service Tecnician',
  learningOutcome: [
    'Recognize the key components examined in a 7 point inspection',
    'Compare the three different types of tire punctures and understand the appropriate repairs for each',
    'Demonstrate safe work practices in an automotive shop setting',
    'Locate educational resources and supports available to become an Automotive Service Technician',
    'Acknowledge the duties of an Automotive Service Technician',
  ],
  itaResource: [
    'Roadside Survival',
    'Safety Considerations',
    'Tire change and repair',
    'Becoming an Automotive Service Tech',
  ],
  projectDescription:
    'Students will explore aspects of the Automotive Service Technician’s role and gain practical knowledge and experience by performing a 7 point inspection as well as assessing and repairing a flat tire',
  ppeRequirement: [
    'Safety Glasses (Eye Protection)',
    ' Gloves(optional)',
    'Steel Toe Boot (Close Toe)',
    ' Hearing Protection',
  ],
  materialNeeded:
    'Tru-flat’ tire plug repair kit. Cost: $30-85\nSpare tires on rims',
  equipmentNeeded: [
    'Demonstration vehicle',
    'Wheel chocks',
    'Floor jack',
    'Jack stands',
    'Lug nut wrench (breaker bar) or impact wrench',
    'Torque wrench',
    'Drill with 1/8 inch bit',
  ],
  dailyPlan: [
    'Intro to Automotive, tools, safety & daily objective',
    'Introduce 7 point inspection',
    '7 point inspection scavenger hunt worksheet',
    'Review worksheet',
    'Break',
    'Discuss tires and the location of puncture & tear',
    'Remove tire & repair flat activity',
    'Clean Up',
    'Buffer time',
    'End Of Lesson Routine:',
    'Project show case, handouts & next steps…',
  ],
  time: [
    '15m',
    '20m',
    '45m',
    '15m',
    '15m',
    '15m',
    '45m',
    '15m',
    '10m',
    '',
    '15m',
  ],
  learningSupports: [
    'Power point and handouts',
    'Handout &  examples',
    'Work as a group',
    'Group discussion',
    'Lift rear of car in prep',
    '',
    'Discuss repairability',
    'Split group, prep tire and car',
    ' Discuss expectation',
    '',
    'Career/Ed opportunities..',
  ],
});
arr.set('Woodwork', {
  name: 'Carpentry',
  learningOutcome: [
    'Identify common hand tools frequently used in carpentry',
    'Acknowledge the important function carpentry plays in everyday life',
    'Recognize education and career opportunities within carpentry trades',
    'Adopt safe workshop practices',
    'Describe the components that make up a framed window',
  ],
  itaResource: [
    'Workshop Safety & Intro to Hand Tools',
    'Overview of Working Conditions',
    'Lay Out a Full Height Wall',
  ],
  projectDescription:
    'Students will construct a bench built with 2x4. Each side of the bench will model the construction of a framed window. Students will be introduced to key terminology related to framing as well as gain basic carpentry experience that will help their transition into a foundation course or satisfy their curiosity',
  ppeRequirement: [
    'Safety Glasses (Eye Protection)',
    'Steel Toe Boot (Close Toe)',
    ' Hearing Protection',
  ],
  equipmentNeeded: [
    'Claw Hammer',
    ' Measuring Tape',
    'Speed Square or Combination Square',
    ' Carpenter’s Level (spirit level)',
    ' Carpenter’s Pencil',
    'Hand Saw or Mitre Saw',
  ],
  materialNeeded: '2”x 4”\n3” Common nail',
  dailyPlan: [
    'Introduction to carpentry, tools and daily objectives ',
    'Stock layout: measure and prepare',
    'Stock breakout: cut 2”x4” to length with hand or miter saw as available',
    'Fit and finish: square edges and clean up saw cuts',
    'Break',
    'Discuss assembly process: eg. nailing pattern and position as well as the relevancy of the bench design',
    'Assembly',
    'Clean Up',
    'Buffer time',
    'End Of Lesson Routine:',
    'Project show case, handouts & next steps…',
  ],
  time: [
    '15m',
    '30m',
    '30-45m',
    '15m',
    '15m',
    '20m',
    '45m',
    '15m',
    '10m',
    '',
    '15m',
  ],
  learningSupports: [
    'Power point and handouts',
    'Quick demo of the process',
    'Discuss safety points such as proper use of a hand saw',
    'Help prepare for assembly',
    '',
    'Explain similarity between project and window design',
    'Refer to drawing & part list',
    'Discuss expectation',
    '',
    '',
    'Career/Ed opportunities…',
  ],
});
arr.set('SolarPower', {
  name: 'Electrician & Electronics',
  learningOutcome: [
    'Explain the 4 components that make up a basic electrical circuit',
    'Assess appropriate voltage and amperage for specific loads',
    'Prepare a circuit that is suitable to power a 1 volt electric motor',
    'Recognize career and education opportunities in the electrical field',
  ],
  itaResource: [
    'How to Become an Electrician',
    'Electrical Hazards and Safety',
    'Robot Application in the Real World',
    'PlayBook',
  ],
  projectDescription:
    'Students will explore the field of electrical through a fun and interactive project. The project will include building and testing a functional mini solar panel that can be configured to charge phones and power a miniature powered solar car',
  ppeRequirement: ['Safety Glasses (Eye Protection)'],
  materialNeeded:
    "'Mini solar cells (.5v)\nElectrical tape\n1 volt electric motors\nCardboard\nConductive copper tape (1/4”)\n22 gauge wire and/or phone charging cable\nGears and drive train for 2mm drive shaft\nVarious materials for chassis and frame",
  equipmentNeeded: ['Multimeter', 'Glue Gun'],
  dailyPlan: [
    'Introduction to trade and lesson topics',
    'Multimeter basics',
    'Introduce solar panels and parallel vs series circuits',
    'Create a 5v circuit to charge a phone',
    'Break',
    'Introduce 1 volt motor and AC vs DC power',
    'Create solar vehicle & appropriate circuit',
    'Clean Up',
    'Buffer time',
    'End Of Lesson Routine:',
    'Project show case, handouts & next steps…	15m	Career/Ed opportunities..',
  ],
  time: [
    '20m',
    '15m',
    '30m',
    '30m',
    '15m',
    '15m',
    '45m',
    '15m',
    '10m',
    '',
    '15m',
  ],
  learningSupports: [
    'Power point presentation',
    'How to use and test',
    'Pros & cons. Test circuits',
    'Test circuit, try on old phone',
    '',
    'Discuss pros and cons ',
    'Hand out supplies',
    ' Explain objective',
    '',
    '',
    'Career/Ed opportunities..',
  ],
});

arr.set('MetalTrades', {
  name: 'Welding & Tinsmith',
  learningOutcome: [
    'Explain the function of basic metalworking tools and equipment',

    'Find post-secondary institutions that offer metal trades training within their region',
    'Adopt safe practice with various metalworking tools/equipment',
    'Recognize that tools/machines should always be used only for their intended purpose',
    'Acknowledge the importance of careers in the trade',
    'Recognize career opportunity’s in related trade',
  ],
  itaResource: [
    'Youth Explore Trades Skills Metal Work– Introduction to metalwork',
    'ITA Makers Club',
    'Youth Explore Trades Skills Automotive Service Technician-Welding',
    'ITA Metal Tools Introduction To Hand Tools Power Point presentation',
    'Career Exploration Metal Trades',
  ],
  dailyPlan: [
    'Introduction to project, tools and relation to metalworking trades',
    'Stock Breakout: Cut sheet metal, file burs centre punch',
    'Cut pedal out of sheet metal circles and leafs out of scrap',
    'Cut and texture round bar',
    'Break',
    'Spot weld petals and leafs',
    'Final touch: Bend petals to get desired shapes',
    'Project show case',
    'Buffer time',
    'End Of Lesson Routine:',
    'Clean Up, Handouts & Class Reminder etc…..',
  ],
  time: [
    '15m',
    '30-60m',
    '30m',
    '15m',
    '15m',
    '30-45m',
    '30m',
    '20m',
    '10m',
    '',
    '15m',
  ],
  learningSupports: [
    'Power point presentation',
    'Extra cut circles',
    '',
    'Extra cut road bar',
    '',
    'Discuss welding specific PPE',
    '',
    'Discuss Career/Ed opportunity’s',
    '',
    '',
    'Handout ITA/TRU related info',
  ],
  equipmentNeeded: [],
  materialNeeded: '',
  ppeRequirement: [],
  projectDescription: '',
});

arr.set('Welder', {
  name: 'Welding & Tinsmithing',
  learningOutcome: [
    'Explain the function of basic metalworking tools and equipment',
    'Identify post-secondary institutions that offer metal trades training within their region',
    'Adopt safe practice with various metalworking tools/equipment',
    'Recognize that tools/machines should always be used for their intended purpose',
    'Acknowledge the importance of careers utilizing welding and sheet metal work processes',
    'Recognize career opportunities in related trade',
  ],
  itaResource: [
    'Introduction to Metalwork',
    'Playbook',
    'Welding',
    'Introduction To Hand Tools,Power Point',
    'Career Exploration Metal Trades',
  ],
  ppeRequirement: [
    'Safety Glasses (eye protection)',
    'Gloves',
    'Welding PPE: helmet, jacket and gloves (if using welding processes)',
  ],
  projectDescription:
    'Students will explore the artistic side of metal working by crafting a one-of-a-kind metal rose. The construction process will explore basic tinsmith tool and welding processes, while fostering students’ creativity and curiosity.',
  equipmentNeeded: [
    'Aviation Snips (tin snips)',
    ' Hammer',
    'Centre Punch',
    'Flat File & File Card Hacksaw',
    'Dividers',
  ],
  materialNeeded:
    '1/8th round bar or other round stock\nSheet metal, 18 gauge or less. eg. 20, 22…\nBonding agent. eg. welding filament, solder, epoxy, hot glue, etc..',
  dailyPlan: [
    'Introduction to the project, the tools and its relevance to metalworking trades',
    'Stock Breakout: Cut sheet metal, file burrs, centre punch',
    'Cut pedals out of sheet metal circles and leaves out of scrap',
    'Cut and texture round bar',
    'Break',
    'Spot weld petals and leaves',
    'Final touch: Bend petals to get desired shapes',
    'Project show case',
    'Buffer time',
    'End Of Lesson Routine:',
    'Clean Up, Handouts & Class Reminders, etc…..',
  ],
  time: [
    '15m',
    '30-60m',
    '30m',
    '15m',
    '15m',
    '30-45m',
    '30m',
    '20m',
    '10m',
    '',
    '15m',
  ],
  learningSupports: [
    'Power point presentation',
    ' Extra cut circles',
    '',
    'Extra cut round bar',
    '',
    'Discuss welding specific PPE',
    '',
    'Career/Ed opportunity’s…',
    '',
    '',
    'Handout ITA/TRU related info',
  ],
});
export default arr;
